development:
  noreply_email: 'no-reply@chanelink.com'
  agoda_endpoint: 'http://sandbox.xml-ycs.agoda.com/xmlservice.aspx'
  expedia_ar_endpoint: 'https://simulator.expediaquickconnect.com/connect/ar'
  expedia_br_endpoint: 'https://simulator.expediaquickconnect.com/connect/br'
  expedia_bc_endpoint: 'https://simulator.expediaquickconnect.com/connect/bc'
  expedia_parr_endpoint: 'https://simulator.expediaquickconnect.com/connect/parr'
  gta_travel_endpoint: 'https://hotels.demo.gta-travel.com'
  gta_travel_qualifier: 'JNBPAL2'
  gta_travel_username: 'CHANELINK'
  gta_travel_password: 'LINK14'
  support_email: 'support-dev@chanelink.com'
  ctrip_end_point: 'http://58.221.127.196:8090/'
  ctrip_rate_plan: '/Hotel/OTAReceive/HotelRatePlan.asmx'
  ctrip_avail_notif: '/Hotel/OTAReceive/HotelAvailNotif.asmx'
  ctrip_rate_amount_notif: '/Hotel/OTAReceive/HotelRateAmountNotif.asmx'
  ctrip_notif_report: '/Hotel/OTAReceive/NotifReport.asmx'
  orbitz_room_rate_fetch: 'https://ws.owweasyconnect.com/easyconnect/service/midtier/roomratetypefetch'
  orbitz_other: 'https://ws.owweasyconnect.com/xml/service'

staging:
  noreply_email: 'no-reply@chanelink.com'
  agoda_endpoint: 'http://sandbox.xml-ycs.agoda.com/xmlservice.aspx'
  expedia_ar_endpoint: 'https://simulator.expediaquickconnect.com/connect/ar'
  expedia_br_endpoint: 'https://simulator.expediaquickconnect.com/connect/br'
  expedia_bc_endpoint: 'https://simulator.expediaquickconnect.com/connect/bc'
  expedia_parr_endpoint: 'https://simulator.expediaquickconnect.com/connect/parr'
  gta_travel_endpoint: 'https://hotels.demo.gta-travel.com'
  gta_travel_qualifier: 'JNBPAL2'
  gta_travel_username: 'CHANELINK'
  gta_travel_password: 'LINK14'
  support_email: 'support-dev@chanelink.com'
  ctrip_end_point: 'http://58.221.127.196:8090/'
  ctrip_rate_plan: 'http://58.221.127.196:8090/Hotel/OTAReceive/HotelRatePlan.asmx'
  ctrip_avail_notif: 'http://vendor.hotels.test.sh.ctriptravel.com/Hotel/OTAReceive/HotelAvailNotif.asmx'
  ctrip_rate_amount_notif: 'http://vendor.hotels.test.sh.ctriptravel.com/Hotel/OTAReceive/HotelRateAmountNotif.asmx'
  ctrip_notif_report: 'http://vendor.hotels.test.sh.ctriptravel.com/Hotel/OTAReceive/NotifReport.asmx'
  orbitz_room_rate_fetch: 'https://ws.owweasyconnect.com/easyconnect/service/midtier/roomratetypefetch'
  orbitz_other: 'https://ws.owweasyconnect.com/xml/service'

production:
  noreply_email: 'no-reply@chanelink.com'
  agoda_endpoint: 'https://xml-ycs.agoda.com/xmlservice.aspx'
  expedia_ar_endpoint: 'https://ws.expediaquickconnect.com/connect/ar'
  expedia_br_endpoint: 'https://ws.expediaquickconnect.com/connect/br'
  expedia_bc_endpoint: 'https://ws.expediaquickconnect.com/connect/bc'
  expedia_parr_endpoint: 'https://ws.expediaquickconnect.com/connect/parr'
  gta_travel_endpoint: 'https://hotels.gta-travel.com'
  support_email: 'support@chanelink.com'
  ctrip_end_point: 'http://58.221.127.196:8090/'
  ctrip_rate_plan: 'https://vendor.ctrip.com/Hotel/OTAReceive/HotelRatePlan.asmx'
  ctrip_avail_notif: 'https://vendor.ctrip.com/Hotel/OTAReceive/HotelAvailNotif.asmx'
  ctrip_rate_amount_notif: 'https://vendor.ctrip.com/Hotel/OTAReceive/HotelRateAmountNotif.asmx'
  ctrip_notif_report: 'https://vendor.ctrip.com/Hotel/OTAReceive/NotifReport.asmx'
  orbitz_room_rate_fetch: 'https://ws.owweasyconnect.com/easyconnect/service/midtier/roomratetypefetch'
  orbitz_other: 'https://ws.owweasyconnect.com/xml/service'

staging2:
  noreply_email: 'application@chanelink.com'
  agoda_endpoint: 'http://sandbox.xml-ycs.agoda.com/xmlservice.aspx'
  expedia_ar_endpoint: 'https://simulator.expediaquickconnect.com/connect/ar'
  expedia_br_endpoint: 'https://simulator.expediaquickconnect.com/connect/br'
  expedia_bc_endpoint: 'https://simulator.expediaquickconnect.com/connect/bc'
  expedia_parr_endpoint: 'https://simulator.expediaquickconnect.com/connect/parr'
  gta_travel_endpoint: 'https://hotels.demo.gta-travel.com'
  gta_travel_qualifier: 'JNBPAL2'
  gta_travel_username: 'CHANELINK'
  gta_travel_password: 'LINK14'
  support_email: 'support-dev@chanelink.com'
  ctrip_end_point: 'http://58.221.127.196:8090/'
  ctrip_rate_plan: 'http://58.221.127.196:8090/Hotel/OTAReceive/HotelRatePlan.asmx'
  ctrip_avail_notif: 'http://vendor.hotels.test.sh.ctriptravel.com/Hotel/OTAReceive/HotelAvailNotif.asmx'
  ctrip_rate_amount_notif: 'http://vendor.hotels.test.sh.ctriptravel.com/Hotel/OTAReceive/HotelRateAmountNotif.asmx'
  ctrip_notif_report: 'http://vendor.hotels.test.sh.ctriptravel.com/Hotel/OTAReceive/NotifReport.asmx'
  orbitz_room_rate_fetch: 'https://ws.owweasyconnect.com/easyconnect/service/midtier/roomratetypefetch'
  orbitz_other: 'https://ws.owweasyconnect.com/xml/service'

test:
  noreply_email: 'application@chanelink.com'
  agoda_endpoint: 'http://sandbox.xml-ycs.agoda.com/xmlservice.aspx'
  expedia_ar_endpoint: 'https://simulator.expediaquickconnect.com/connect/ar'
  expedia_br_endpoint: 'https://simulator.expediaquickconnect.com/connect/br'
  expedia_bc_endpoint: 'https://simulator.expediaquickconnect.com/connect/bc'
  expedia_parr_endpoint: 'https://simulator.expediaquickconnect.com/connect/parr'
  gta_travel_endpoint: 'https://hotels.demo.gta-travel.com'
  gta_travel_qualifier: 'JNBPAL2'
  gta_travel_username: 'CHANELINK'
  gta_travel_password: 'LINK14'
  support_email: 'support-dev@chanelink.com'
  ctrip_end_point: 'http://58.221.127.196:8090/'
  ctrip_rate_plan: '/Hotel/OTAReceive/HotelRatePlan.asmx'
  ctrip_avail_notif: '/Hotel/OTAReceive/HotelAvailNotif.asmx'
  ctrip_rate_amount_notif: '/Hotel/OTAReceive/HotelRateAmountNotif.asmx'
  ctrip_notif_report: '/Hotel/OTAReceive/NotifReport.asmx'
  orbitz_room_rate_fetch: 'https://ws.owweasyconnect.com/easyconnect/service/midtier/roomratetypefetch'
  orbitz_other: 'https://ws.owweasyconnect.com/xml/service'