development:
  noreply_email: 'application@chanelink.com'
#  noreply_email: 'noreply@chanelink.com'
  agoda_endpoint: 'http://sandbox.xml-ycs.agoda.com/xmlservice.aspx'
  expedia_ar_endpoint: 'https://simulator.expediaquickconnect.com/connect/ar'
  expedia_br_endpoint: 'https://simulator.expediaquickconnect.com/connect/br'
  expedia_bc_endpoint: 'https://simulator.expediaquickconnect.com/connect/bc'
  expedia_parr_endpoint: 'https://simulator.expediaquickconnect.com/connect/parr'
  gta_travel_endpoint: 'https://hotels.demo.gta-travel.com'
  gta_travel_qualifier: 'JNBPAL2'
  gta_travel_username: 'CHANELINK'
  gta_travel_password: 'LINK14'
  # support_email: 'support-dev@chanelink.com'
  support_email: 'application@chanelink.com'

  # Always make this part similar to urls listed in /channel_api_tests directory.
  # Todo: Unsure if this should be put here, or define them within channel classes,
  #       but let us keep them here for now until further arguments arise.
  ctrip_rates_get_endpoint: 'http://58.221.127.196:8090/Hotel/OTAReceive/HotelRatePlan.asmx'
  ctrip_rates_update_endpoint: 'http://58.221.127.196:8090/Hotel/OTAReceive/HotelRateAmountNotif.asmx'
  ctrip_inventories_update_endpoint: 'http://58.221.127.196:8090/Hotel/OTAReceive/HotelAvailNotif.asmx'
  ctrip_asynchronous_endpoint: 'http://58.221.127.196:8090/Hotel/OTAReceive/NotifReport.asmx'

  orbitz_room_rate_fetch: 'https://ws.owweasyconnect.com/easyconnect/service/midtier/roomratetypefetch'
  orbitz_other: 'https://ws.owweasyconnect.com/xml/service'

staging:
  # noreply_email: 'noreply@chanelink.com'
  noreply_email: 'application@chanelink.com'
  agoda_endpoint: 'http://sandbox.xml-ycs.agoda.com/xmlservice.aspx'
  expedia_ar_endpoint: 'https://simulator.expediaquickconnect.com/connect/ar'
  expedia_br_endpoint: 'https://simulator.expediaquickconnect.com/connect/br'
  expedia_bc_endpoint: 'https://simulator.expediaquickconnect.com/connect/bc'
  expedia_parr_endpoint: 'https://simulator.expediaquickconnect.com/connect/parr'
  gta_travel_endpoint: 'https://hotels.demo.gta-travel.com'
  gta_travel_qualifier: 'JNBPAL2'
  gta_travel_username: 'CHANELINK'
  gta_travel_password: 'LINK14'
  support_email: 'support@chanelink.com'
  # support_email: 'application@chanelink.com'

  ctrip_rates_get_endpoint: 'http://58.221.127.196:8090/Hotel/OTAReceive/HotelRatePlan.asmx'
  ctrip_rates_update_endpoint: 'http://58.221.127.196:8090/Hotel/OTAReceive/HotelRateAmountNotif.asmx'
  ctrip_inventories_update_endpoint: 'http://58.221.127.196:8090/Hotel/OTAReceive/HotelAvailNotif.asmx'
  ctrip_asynchronous_endpoint: 'http://58.221.127.196:8090/Hotel/OTAReceive/NotifReport.asmx'

  orbitz_room_rate_fetch: 'https://ws.owweasyconnect.com/easyconnect/service/midtier/roomratetypefetch'
  orbitz_other: 'https://ws.owweasyconnect.com/xml/service'

production:
  # noreply_email: 'noreply@chanelink.com'
  noreply_email: 'application@chanelink.com'
  agoda_endpoint: 'https://xml-ycs.agoda.com/xmlservice.aspx'
  expedia_ar_endpoint: 'https://ws.expediaquickconnect.com/connect/ar'
  expedia_br_endpoint: 'https://ws.expediaquickconnect.com/connect/br'
  expedia_bc_endpoint: 'https://ws.expediaquickconnect.com/connect/bc'
  expedia_parr_endpoint: 'https://ws.expediaquickconnect.com/connect/parr'
  gta_travel_endpoint: 'https://hotels.gta-travel.com'
  support_email: 'support@chanelink.com'
  # support_email: 'application@chanelink.com'
  ctrip_rates_get_endpoint: 'https://vendor.ctrip.com/Hotel/OTAReceive/HotelRatePlan.asmx'
  ctrip_rates_update_endpoint: 'http://vendor.ctrip.com/Hotel/OTAReceive/HotelRateAmountNotif.asmx'
  ctrip_inventories_update_endpoint: 'http://vendor.ctrip.com/Hotel/OTAReceive/HotelAvailNotif.asmx'
  ctrip_asynchronous_endpoint: 'https://vendor.ctrip.com/Hotel/OTAReceive/NotifReport.asmx'

  orbitz_room_rate_fetch: 'https://ws.owweasyconnect.com/easyconnect/service/midtier/roomratetypefetch'
  orbitz_other: 'https://ws.owweasyconnect.com/xml/service'

staging2:
  noreply_email: 'application@chanelink.com'
  agoda_endpoint: 'http://sandbox.xml-ycs.agoda.com/xmlservice.aspx'
  expedia_ar_endpoint: 'https://simulator.expediaquickconnect.com/connect/ar'
  expedia_br_endpoint: 'https://simulator.expediaquickconnect.com/connect/br'
  expedia_bc_endpoint: 'https://simulator.expediaquickconnect.com/connect/bc'
  expedia_parr_endpoint: 'https://simulator.expediaquickconnect.com/connect/parr'
  gta_travel_endpoint: 'https://hotels.demo.gta-travel.com'
  gta_travel_qualifier: 'JNBPAL2'
  gta_travel_username: 'CHANELINK'
  gta_travel_password: 'LINK14'
  support_email: 'application@chanelink.com'

  ctrip_rates_get_endpoint: 'http://58.221.127.196:8090/Hotel/OTAReceive/HotelRatePlan.asmx'
  ctrip_rates_update_endpoint: 'http://58.221.127.196:8090/Hotel/OTAReceive/HotelRateAmountNotif.asmx'
  ctrip_inventories_update_endpoint: 'http://58.221.127.196:8090/Hotel/OTAReceive/HotelAvailNotif.asmx'
  ctrip_asynchronous_endpoint: 'http://58.221.127.196:8090/Hotel/OTAReceive/NotifReport.asmx'

  orbitz_room_rate_fetch: 'https://ws.owweasyconnect.com/easyconnect/service/midtier/roomratetypefetch'
  orbitz_other: 'https://ws.owweasyconnect.com/xml/service'

test:
  noreply_email: 'application@chanelink.com'
  agoda_endpoint: 'http://sandbox.xml-ycs.agoda.com/xmlservice.aspx'
  expedia_ar_endpoint: 'https://simulator.expediaquickconnect.com/connect/ar'
  expedia_br_endpoint: 'https://simulator.expediaquickconnect.com/connect/br'
  expedia_bc_endpoint: 'https://simulator.expediaquickconnect.com/connect/bc'
  expedia_parr_endpoint: 'https://simulator.expediaquickconnect.com/connect/parr'
  gta_travel_endpoint: 'https://hotels.demo.gta-travel.com'
  gta_travel_qualifier: 'JNBPAL2'
  gta_travel_username: 'CHANELINK'
  gta_travel_password: 'LINK14'
  support_email: 'application@chanelink.com'

  ctrip_rates_get_endpoint: 'http://58.221.127.196:8090/Hotel/OTAReceive/HotelRatePlan.asmx'
  ctrip_rates_update_endpoint: 'http://58.221.127.196:8090/Hotel/OTAReceive/HotelRateAmountNotif.asmx'
  ctrip_inventories_update_endpoint: 'http://58.221.127.196:8090/Hotel/OTAReceive/HotelAvailNotif.asmx'
  ctrip_asynchronous_endpoint: 'http://58.221.127.196:8090/Hotel/OTAReceive/NotifReport.asmx'

  orbitz_room_rate_fetch: 'https://ws.owweasyconnect.com/easyconnect/service/midtier/roomratetypefetch'
  orbitz_other: 'https://ws.owweasyconnect.com/xml/service'