source 'http://rubygems.org'

gem 'rails', '3.0.3'

gem 'rake','0.8.7'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'mysql2', '0.2.6'

# GUID generator
gem 'uuidtools', '2.1.2'

# client side validation
gem 'client_side_validations', '3.1.4'

# pagination
gem 'will_paginate', '3.0'

# Paperclip: for image resizing
gem 'paperclip', '2.4'

# Delayed job
gem 'delayed_job_active_record', '0.3.2'
gem 'daemons'

# ssl gem
gem "bartt-ssl_requirement", "~> 1.2.7", :require => 'ssl_requirement'

# to detect visitor location
gem 'geocoder', '1.1.0'

# amazon s3
gem 'aws-s3', '0.6.2'

# jammit for asset packaging
gem 'jammit', '0.6.3'

# captcha for registration
gem 'recaptcha', '0.3.1', :require => "recaptcha/rails"

gem 'sitemap_generator', '2.1.8'

# prawn pdf writer
gem 'prawn', '1.0.0.rc1'

# nokogiri html/xml parser
# gem 'nokogiri', '1.4.4'
gem 'nokogiri'

gem 'fastercsv', "1.5.5"

gem 'cancan', "1.6.10"

gem 'whenever', '0.9.0'

gem "equivalent-xml", "~> 0.4.0"

gem 'unscoped_associations', "0.4.2"

gem 'attr_encrypted', "1.3.2"

group :development, :test do
  gem 'rspec-rails'
  gem 'capybara'
  # gem 'selenium-webdriver'
  gem 'show_me_the_cookies'
  gem 'spork', github: 'sporkrb/spork'
  gem "spork-rails"
end

# Use unicorn as the web server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger (ruby-debug for Ruby 1.8.7+, ruby-debug19 for Ruby 1.9.2+)
# gem 'ruby-debug'
# gem 'ruby-debug19'

# Bundle the extra gems:
# gem 'bj'
# gem 'nokogiri'
# gem 'sqlite3-ruby', :require => 'sqlite3'
# gem 'aws-s3', :require => 'aws/s3'

# Bundle gems for the local environment. Make sure to
# put test-only gems in this group so their generators
# and rake tasks are available in development mode:
# group :development, :test do
#   gem 'webrat'
# end
